### ISSUE TITLE
Trouble compiling in windows

### ISSUE THREAD

**Issue by cryptrol** [floodyberry/scrypt-jane#1]
I am using Mingw with gcc version 4.7 but there are some lines that choke to the compiler :

<pre>
$ gcc -O3 -DSCRYPT_KECCAK512 -DSCRYPT_SALSA -DSCRYPT_CHOOSE_COMPILETIME scrypt-
jane.c
C:\Users\user\AppData\Local\Temp\ccg4co7k.s: Assembler messages:
C:\Users\user\AppData\Local\Temp\ccg4co7k.s:23: Warning: .type pseudo-op used outside of .def/.endef ignored.
C:\Users\user\AppData\Local\Temp\ccg4co7k.s:23: Error: junk at end of line, firs
t unrecognized character is `h'
C:\Users\user\AppData\Local\Temp\ccg4co7k.s:24: Warning: .size pseudo-op used outside of .def/.endef ignored.
C:\Users\user\AppData\Local\Temp\ccg4co7k.s:24: Error: junk at end of line, firs
t unrecognized character is `h'
</pre>

**Comment by floodyberry** [comment]
I'll take a look. I don't use MinGW so I often test sporadically or not at all on it.

**Comment by floodyberry** [comment]
3137414c67a536c2a11b52dbefdf21dd657b3403 works under my MinGW now (MinGW 3.20 / gcc 4.6)

**Comment by cryptrol** [comment]
Works also on current MinGW and gcc4.7.2.
Thank you very much.
