### ISSUE TITLE
static declaration of 'scrypt_ChunkMix_avx' follows non-static declaration when compiling with intrinsics on x64

### ISSUE THREAD

**Issue by Thirtybird** [floodyberry/scrypt-jane#2]
Including this library into the miner for YaCoin so it compiles under MinGW, it compiles just fine under x86.  Setting -DCPU_X86_FORCE_INTRINSICS causes the following error:

In file included from scrypt-jane/code/scrypt-jane-chacha.h:14:0,
                 from scrypt-jane/code/scrypt-jane-romix.h:2,
                 from scrypt-jane/scrypt-jane.c:12:
scrypt-jane/code/scrypt-jane-mix_chacha-avx.h:265:1: error: static declaration of 'scrypt_ChunkMix_avx' follows non-static declaration
scrypt-jane/code/scrypt-jane-mix_chacha-avx.h:149:1: note: previous declaration of 'scrypt_ChunkMix_avx' was here

also, looking at the code, this may be important, but I'm forcing AVX with the -march directive

**Comment by floodyberry** [comment]
It should be fixed in ba3983d0ce7e520989f7e914a5cd05ad4ffeefab. I can't settle on a decent method to support both inline asm, and intrinsics for MSVC-64, and #define gymnastics to select the correct version got a little out of sync

**Comment by Thirtybird** [comment]
I pulled the latest, and can confirm that it compiles with the -DCPU_X86_FORCE_INTRINSICS under MinGW 64 now.  Sometimes I think supporting the different possible environments is harder than writing the code to do the work...  Anyway, thank you for the quick turnaround.
