### ISSUE TITLE
Does not compile under Mac OS X

### ISSUE THREAD

**Issue by Kosmatik** [floodyberry/scrypt-jane#3]
Had to change malloc.h include to stdlib.h in scrypt-jane.c for it to stop nagging about not being able to locate malloc.h, but now getting compile errors. Something to do with with sse, sse2, ssse3 or avx in scrypt-jane-portable-x86.h

$ gcc scrypt-jane.c scrypt-jane.c -O3 -m64 -DSCRYPT_SALSA64 -DSCRYPT_BLAKE512
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:5:Alignment too large: 15. assumed.
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:178:suffix or operands invalid for `ja'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:202:suffix or operands invalid for`jne'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:207:Unknown pseudo-op: .type
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:207:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:208:Unknown pseudo-op: .size
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:208:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:212:Alignment too large: 15. assumed.
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:397:suffix or operands invalid for `ja'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:421:suffix or operands invalid for`jne'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:426:Unknown pseudo-op: .type
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:426:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:427:Unknown pseudo-op: .size
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:427:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:5:Alignment too large: 15. assumed.
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:178:suffix or operands invalid for `ja'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:202:suffix or operands invalid for`jne'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:207:Unknown pseudo-op: .type
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:207:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:208:Unknown pseudo-op: .size
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:208:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:212:Alignment too large: 15. assumed.
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:397:suffix or operands invalid for `ja'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:421:suffix or operands invalid for`jne'
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:426:Unknown pseudo-op: .type
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:426:Rest of line ignored. 1st junk character valued 115 (s).
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:427:Unknown pseudo-op: .size
/var/folders/z2/d2tynst114n6bc3cfh672n_40000gn/T//ccMD3jw5.s:427:Rest of line ignored. 1st junk character valued 115 (s).

**Comment by floodyberry** [comment]
What compiler version does OS X use?

I know the .type/.size stuff is from asm_naked_fn_end() where I tried? to give some help to the debug data (otherwise it doesn't know what function it's in when you step through the assembly), but it can be stripped out safely, e.g. using the OS_WINDOWS/CDECL block at https://github.com/floodyberry/scrypt-jane/blob/master/code/scrypt-jane-portable-x86.h#L164.

The alignment and jump op errors are odd. I'll see if I can get OS X running in a vm to test things out

**Comment by Kosmatik** [comment]
$ gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

**Comment by Kosmatik** [comment]
Also commenting line 164-168 and the #endif still gives exactly the same errors.

**Comment by floodyberry** [comment]
ok, I tracked down some differences with how OS X works and worked around a bug with its assembler. Only downside for OS X right now is that AVX instructions aren't supported by the gcc assembler, and clang can't be used for AVX because its assembler doesn't support .intel_syntax, but everything else appears to work

**Comment by Kosmatik** [comment]
Yep I saw during configure that no avx is supported, that's alright ssse3 is not that far behind. Thanks for the update.

**Comment by edwardvalentini** [comment]
is there any resolution to this?  I am not able to get scrypt-jane to compile on osx either.
