### ISSUE TITLE
QT creator comile error in ASM on mac os x.

### ISSUE THREAD

**Issue by Kosmatik** [floodyberry/scrypt-jane#4]
Getting error during qt creator 5.0.2 build process in scrypt-jane-portable-x86.h lines 241-244

scrypt-jane/code/scrypt-jane-portable-x86.h:241: error: unknown token in expression
        a2(mov [%1 + 0], eax)
        ^

also line 250

scrypt-jane/code/scrypt-jane-portable-x86.h:250: error: invalid instruction mnemonic 'prefix'
        asm_gcc_parms() : "+a"(flags) : "S"(regs)  : "%ecx", "%edx", "cc"
        ^

**Comment by floodyberry** [comment]
Those look like llvm (clang) errors. If you're intending to use clang, are you building it with the "-no-integrated-as" flag? clang's internal assembler doesn't support the ".intel_syntax" feature.

**Comment by Kosmatik** [comment]
That fixed it as well, thanks!
